FROM ghcr.io/playtron-os/playtron-os:latest
RUN dnf5 group install -y --allowerasing kde-desktop
RUN dnf5 clean all && rm -r -f /boot/.* /usr/etc /var/cache/* /var/log/akmods/* && bootc container lint
